//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcomApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderItem
    {
        public int ORDERITEMID { get; set; }
        public Nullable<int> ORDERID { get; set; }
        public Nullable<int> PRODUCTID { get; set; }
        public Nullable<int> QUANTITY { get; set; }
        public Nullable<decimal> PRICE { get; set; }
        public Nullable<bool> RETURNABLE { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Product Product { get; set; }
    }
}
